
services:
  mymaster01:
    build: .
    image: hadoop-ha:1.0
    container_name: mymaster01
    hostname: mymaster01
    ports:
      - "8481:8480" #yarn
      - "9878:9870" #nn UI
     # - "8081:8088" #jn
    command: sleep infinity
    volumes:
      - ./config:/opt/hadoop/etc/hadoop
      - ./name/nn1:/opt/hadoop/dfs/name
     
    networks:
      - cluster-network

  mymaster02:
    build: .
    image: hadoop-ha:1.0
    container_name: mymaster02
    hostname: mymaster02
    ports:      
      - "9879:9870" 
      - "8482:8480"
     # - "8082:8088"
    command: sleep infinity
    volumes:
      - ./config:/opt/hadoop/etc/hadoop
      - ./name/nn2:/opt/hadoop/dfs/name
      
    networks:
      - cluster-network

  myworker01:
    build: .
    image: hadoop-ha:1.0
    container_name: myworker01
    hostname: myworker01 
    ports: 
     - "8083:8088" 
    command: sleep infinity
    volumes:
      - ./config:/opt/hadoop/etc/hadoop
      - ./journal/jn1:/opt/hadoop/dfs/journal
    networks:
      - cluster-network

  myworker02:
    build: .
    image: hadoop-ha:1.0
    container_name: myworker02
    hostname: myworker02    
    ports:
      - "8084:8088"     
    command: sleep infinity
    volumes:
      - ./config:/opt/hadoop/etc/hadoop
      - ./journal/jn2:/opt/hadoop/dfs/journal
    networks:
      - cluster-network

  myworker03:
    build: .
    image: hadoop-ha:1.0
    container_name: myworker03
    hostname: myworker03   
    ports:
       - "8085:8088"     
    command: sleep infinity
    volumes:
      - ./config:/opt/hadoop/etc/hadoop
      - ./journal/jn3:/opt/hadoop/dfs/journal
      
    networks:
      - cluster-network

networks:
  cluster-network:
    driver: bridge
